In [1]:
import pandas as pd
import os

path = "MRIs_IMAGES_FILTERED_NOMASKS"

all_paths = os.listdir(path)
for i in range(len(all_paths)):
    all_paths[i] = os.path.join(path, all_paths[i])

df = pd.DataFrame(all_paths, columns=["subject"])

df.to_csv("subject_paths.csv", index=False)

In [2]:
print(len(df))

756

In [9]:
import os
import pandas as pd

def generate_unique_subject_ids(df, subject_col='subject'):
    """
    Generates unique subject IDs based on the 'subject' column.
    If a subject ID repeats, appends a count to make it unique.
    
    Args:
        df (pd.DataFrame): Input dataframe with a column containing subject paths.
        subject_col (str): Name of the column with the subject paths.
        
    Returns:
        pd.DataFrame: DataFrame with a new column 'subject_id' containing unique IDs.
    """
    id_counts = {}  # to keep track of occurrences
    subject_ids = []

    for path in df[subject_col]:
        # Extract base ID
        base_id = os.path.basename(path).split('.')[0]
            
        subject_ids.append(base_id)
    
    df['subject_id'] = subject_ids
    return df

In [10]:
df = generate_unique_subject_ids(df)

In [12]:
df['subject_id'].unique()

array(['ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20100601172719474_S78802_I176204',
       'ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20110216143748651_S97012_I217793',
       'ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070209205734937_S22295_I39026',
       'ADNI_002_S_0685_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081015130623197_S55756_I120998',
       'ADNI_016_S_1121_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080308123438915_S44322_I96243',
       'ADNI_099_S_0090_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20080414114559934_S26174_I102436',
       'ADNI_022_S_1394_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070816140733869_S34317_I68081',
       'ADNI_073_S_0909_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071219133102329_S42927_I85580',
       'ADNI_114_S_0979_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081230153918289_S60749_I132437',
       'ADNI_126_S_1221_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070412185035131_S25456_I48971',
       'ADNI_114_S_0173_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20090717154627185_S64287_I149645',
       'ADNI_035_S_0997_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080223130031033_S44884_I91728',
       'ADNI_023_S_0042_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080111111455658_S43243_I87035',
       'ADNI_013_S_1186_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070918121138617_S36952_I73561',
       'ADNI_005_S_1224_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20080430162944735_S49188_I104396',
       'ADNI_022_S_0130_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080229154208467_S45581_I94418',
       'ADNI_032_S_0479_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080613154037775_S50883_I109528',
       'ADNI_127_S_0844_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070731205023388_S32359_I63623',
       'ADNI_011_S_0053_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20061206182608127_S15006_I31999',
       'ADNI_136_S_0579_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20080223194059268_S44768_I92092',
       'ADNI_023_S_0963_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070806122430634_S29233_I65008',
       'ADNI_033_S_1308_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071028101527696_S39227_I78955',
       'ADNI_094_S_0711_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070802211020289_S26462_I64360',
       'ADNI_141_S_0697_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080220165125448_S18466_I91234',
       'ADNI_023_S_1126_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081101202706399_S23441_I124874',
       'ADNI_033_S_0923_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100105141824977_S57389_I162095',
       'ADNI_053_S_0507_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20090730115525280_S67537_I151131',
       'ADNI_027_S_0256_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070808171933076_S29476_I66003',
       'ADNI_099_S_0880_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070818142538528_S30548_I68594',
       'ADNI_057_S_1371_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071101175535150_S40935_I80252',
       'ADNI_130_S_0289_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070801174842453_S28723_I63720',
       'ADNI_023_S_1247_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070427204448475_S26860_I52142',
       'ADNI_005_S_0610_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070923122713025_S37098_I74586',
       'ADNI_023_S_0030_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_2_Br_20081001140030344_S20024_I118795',
       'ADNI_141_S_0767_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20081022121223841_S27492_I122712',
       'ADNI_016_S_1326_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071029104357175_S40724_I79322',
       'ADNI_023_S_0963_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100106095640338_S75642_I162350',
       'ADNI_002_S_0938_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071110105459349_S41835_I81316',
       'ADNI_041_S_1412_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080229173929520_S45603_I94536',
       'ADNI_053_S_0389_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070809203722621_S22123_I66639',
       'ADNI_024_S_1063_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070731170617965_S21525_I63392',
       'ADNI_023_S_0217_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070918124646846_S36959_I73595',
       'ADNI_099_S_0040_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081211163149255_S60498_I130113',
       'ADNI_099_S_0533_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070403123928568_S24035_I47939',
       'ADNI_094_S_0526_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070731182838774_S14559_I63467',
       'ADNI_016_S_0538_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100114160940971_S55407_I163713',
       'ADNI_098_S_0269_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070812145531201_S29779_I67236',
       'ADNI_127_S_1427_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080220144535548_S37934_I91130',
       'ADNI_116_S_0649_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070508155719067_S26947_I53827',
       'ADNI_005_S_0324_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20061212171807772_S12599_I32892',
       'ADNI_031_S_1209_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071002184608174_S36417_I76662',
       'ADNI_099_S_0958_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20061228154542455_S20493_I34594',
       'ADNI_033_S_0567_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20091012180258650_S68613_I157037',
       'ADNI_029_S_1215_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081017101050030_S55455_I121807',
       'ADNI_033_S_0567_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_2_Br_20081003121001991_S14572_I119126',
       'ADNI_127_S_0259_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080414160909721_S47606_I102520',
       'ADNI_031_S_0568_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080626141200113_S51249_I111227',
       'ADNI_027_S_0403_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20061222191351273_S13717_I34181',
       'ADNI_073_S_0089_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_2_Br_20081006105102890_S11161_I119227',
       'ADNI_067_S_0059_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070111011430177_S10518_I35906',
       'ADNI_057_S_0934_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081104084856011_S57841_I125130',
       'ADNI_011_S_0241_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20090511112336367_S65417_I143466',
       'ADNI_141_S_0851_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20071110130910139_S41581_I81508',
       'ADNI_099_S_0372_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080602141039549_S48874_I108071',
       'ADNI_023_S_0926_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20061203145738457_S19391_I31550',
       'ADNI_022_S_0961_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080513172701764_S49362_I105321',
       'ADNI_067_S_0290_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20080131140522955_S15130_I89124',
       'ADNI_082_S_0928_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071101185402906_S41422_I80342',
       'ADNI_082_S_0363_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070213172657494_S13016_I39733',
       'ADNI_027_S_0408_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20101111105300086_S85295_I204764',
       'ADNI_114_S_0458_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070213195524466_S14111_I39844',
       'ADNI_051_S_1131_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20081017124840816_S54675_I121965',
       'ADNI_067_S_0290_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20061229185114184_S15130_I34854',
       'ADNI_036_S_1023_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070806143820211_S24338_I65104',
       'ADNI_013_S_0325_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070517130305186_S13523_I54668',
       'ADNI_023_S_0376_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080116082909377_S41959_I87511',
       'ADNI_141_S_1255_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080515133954783_S49216_I105841',
       'ADNI_023_S_0604_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_2_Br_20081002113933605_S15677_I119026',
       'ADNI_082_S_1079_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20080318141316082_S46360_I98824',
       'ADNI_053_S_1044_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070802192047518_S21256_I64202',
       'ADNI_023_S_0093_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070727132450689_S26505_I62416',
       'ADNI_027_S_1081_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20071028195713680_S38366_I79200',
       'ADNI_033_S_0733_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070921083643279_S37300_I73993',
       'ADNI_109_S_1014_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081110163401898_S58146_I125924',
       'ADNI_127_S_0622_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100108161032328_S69355_I162942',
       'ADNI_073_S_0386_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20101110122452361_S86846_I204155',
       'ADNI_007_S_0344_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20101029122430016_S87406_I200338',
       'ADNI_023_S_0625_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070427201233285_S27235_I52102',
       'ADNI_082_S_0641_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070213182825664_S15700_I39784',
       'ADNI_141_S_0982_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080522181021395_S50074_I106616',
       'ADNI_057_S_1379_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20090514103130382_S66419_I143815',
       'ADNI_062_S_1182_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080313114246133_S46207_I97168',
       'ADNI_099_S_0372_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070807111434336_S32293_I65455',
       'ADNI_016_S_1263_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070804133952972_S27303_I64621',
       'ADNI_128_S_1407_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081020135715099_S56243_I122386',
       'ADNI_116_S_0487_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080225095154223_S33715_I92424',
       'ADNI_005_S_0324_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080430143333279_S49114_I104356',
       'ADNI_023_S_0061_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20090127163851356_S61044_I134693',
       'ADNI_141_S_0853_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071119105641283_S27837_I82752',
       'ADNI_941_S_1202_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070801201337815_S25680_I63874',
       'ADNI_005_S_0602_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070815094211659_S25966_I67681',
       'ADNI_031_S_1066_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20080225191153235_S32777_I92682',
       'ADNI_007_S_1222_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20080307173800854_S46092_I96047',
       'ADNI_002_S_0413_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070319120107557_S13894_I45121',
       'ADNI_007_S_0293_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070118021707480_S21503_I36544',
       'ADNI_136_S_0299_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070809225255628_S32247_I66749',
       'ADNI_109_S_0967_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20090701142450761_S65787_I147521',
       'ADNI_041_S_0446_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070904211409623_S33007_I71610',
       'ADNI_099_S_0372_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070418084733384_S22214_I49538',
       'ADNI_126_S_0405_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070209175521333_S15644_I38807',
       'ADNI_005_S_1224_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100602125634140_S83052_I176465',
       'ADNI_057_S_0643_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100111144202874_S70433_I163004',
       'ADNI_057_S_0818_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070910185456783_S29057_I72293',
       'ADNI_094_S_1314_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20101110152111154_S81494_I204326',
       'ADNI_133_S_0912_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_2_Br_20081008095217990_S49520_I119632',
       'ADNI_003_S_1074_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080221161737185_S45439_I91408',
       'ADNI_027_S_1254_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070327170240439_S25763_I47232',
       'ADNI_023_S_0625_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081013171424457_S54690_I120455',
       'ADNI_022_S_0924_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070712160908877_S19446_I59579',
       'ADNI_141_S_1245_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070923141808240_S37966_I74752',
       'ADNI_029_S_1318_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20071029185652390_S41201_I79599',
       'ADNI_037_S_0588_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20090313102741046_S34411_I138829',
       'ADNI_114_S_1103_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070419174921638_S23240_I49761',
       'ADNI_062_S_0535_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070424113555541_S24055_I50438',
       'ADNI_033_S_1098_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070306095209723_S22792_I42831',
       'ADNI_130_S_0102_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070212204139243_S10747_I39463',
       'ADNI_062_S_0793_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070424124729305_S27206_I50537',
       'ADNI_011_S_0241_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20061206190047259_S12088_I32020',
       'ADNI_041_S_0679_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080223162006972_S45244_I91801',
       'ADNI_023_S_0084_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070427193110994_S25511_I52043',
       'ADNI_116_S_0392_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080206163640894_S23632_I89657',
       'ADNI_037_S_0501_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100226111943768_S74155_I166907',
       'ADNI_131_S_0441_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20071226102634704_S25266_I86106',
       'ADNI_002_S_0938_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070713122757058_S29621_I60043',
       'ADNI_027_S_0074_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20061222172044442_S16322_I34109',
       'ADNI_127_S_0925_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080617171022464_S51171_I109905',
       'ADNI_136_S_0196_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080516161530340_S49468_I105974',
       'ADNI_130_S_0783_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081024091750867_S55883_I123411',
       'ADNI_002_S_1070_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081224110136214_S60780_I132210',
       'ADNI_052_S_1352_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070727121310415_S27550_I62327',
       'ADNI_005_S_0602_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20061212144916449_S17240_I32800',
       'ADNI_033_S_0920_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070304121025723_S19288_I42481',
       'ADNI_027_S_1385_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070330094917890_S28132_I47578',
       'ADNI_133_S_0433_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20071111133200213_S23400_I81618',
       'ADNI_016_S_1326_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080415141935346_S47893_I102683',
       'ADNI_041_S_0314_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20101109120253155_S85270_I203737',
       'ADNI_127_S_0393_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070731200719867_S33203_I63578',
       'ADNI_128_S_1088_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20090313113508313_S35268_I138862',
       'ADNI_005_S_0448_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080611155649175_S50866_I109182',
       'ADNI_027_S_1254_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20090316154022446_S63692_I139078',
       'ADNI_128_S_0608_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070821112310857_S34228_I69376',
       'ADNI_127_S_1032_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080626145345200_S51394_I111300',
       'ADNI_023_S_1247_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081014181110750_S55338_I120819',
       'ADNI_023_S_1126_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080702111646172_S51798_I112225',
       'ADNI_007_S_1206_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100601175816166_S80029_I176243',
       'ADNI_098_S_0896_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20081125161838202_S58297_I128551',
       'ADNI_027_S_0835_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20081023104917407_S56476_I122967',
       'ADNI_006_S_0731_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071027123708871_S38846_I78731',
       'ADNI_011_S_0362_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20101029132643407_S86780_I200465',
       'ADNI_053_S_0621_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20080220134011696_S44457_I91010',
       'ADNI_136_S_0695_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100107103837792_S74028_I162687',
       'ADNI_011_S_0168_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070108232555158_S11605_I35499',
       'ADNI_067_S_0607_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071229185426117_S29073_I86415',
       'ADNI_136_S_0196_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070215194926219_S20812_I40292',
       'ADNI_033_S_0734_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070517155218849_S26802_I54743',
       'ADNI_033_S_1016_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20110222130319826_S94540_I218770',
       'ADNI_007_S_0344_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070727181024077_S30635_I62621',
       'ADNI_094_S_0921_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100108114348885_S75003_I162823',
       'ADNI_036_S_0869_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080125111443364_S31883_I88535',
       'ADNI_027_S_0461_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070327143307540_S23516_I47131',
       'ADNI_041_S_1002_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070806163146718_S23706_I65225',
       'ADNI_941_S_1203_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20101111125927726_S83453_I204856',
       'ADNI_024_S_0985_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071110115916846_S41816_I81409',
       'ADNI_126_S_0680_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070412182036876_S25498_I48936',
       'ADNI_005_S_1224_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070923125912785_S37372_I74622',
       'ADNI_023_S_0855_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071006115113757_S38876_I77030',
       'ADNI_022_S_0096_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070712151035157_S11005_I59460',
       'ADNI_128_S_0229_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080410164245717_S47907_I102221',
       'ADNI_941_S_1311_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080313131657918_S40710_I97340',
       'ADNI_027_S_1387_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20081013122848620_S56409_I120273',
       'ADNI_099_S_0470_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080603182144382_S50408_I108297',
       'ADNI_094_S_1267_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20091202160245913_S69242_I160050',
       'ADNI_041_S_1425_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070917110609443_S36929_I73361',
       'ADNI_141_S_1255_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070411124958080_S25886_I48612',
       'ADNI_062_S_0535_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080702154608194_S51762_I112305',
       'ADNI_018_S_0155_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20090511165123572_S64907_I143567',
       'ADNI_006_S_0498_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20070605122045523_S19763_I55943',
       'ADNI_007_S_0128_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070713104335049_S26557_I59869',
       'ADNI_099_S_0551_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20080225181435042_S43126_I92572',
       'ADNI_127_S_0259_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20061227142504330_S12136_I34366',
       'ADNI_016_S_0769_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20071229174131913_S28898_I86313',
       'ADNI_023_S_0061_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20061130181357306_S10312_I31102',
       'ADNI_128_S_0272_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070819161818170_S20038_I68938',
       'ADNI_041_S_1002_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20100428123020275_S78468_I172091',
       'ADNI_109_S_1183_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20080224144052919_S44976_I92273',
       'ADNI_067_S_0336_MR_MPR-R__GradWarp__B1_Correction__N3__Scaled_Br_20071221161459868_S32534_I85990',
       'ADNI_022_S_0130_MR_MPR-R__GradWarp__B1_Correction__N3_Br_20070712154300162_S11088_I59528',

In [18]:
df['to_txt'] = df['subject_id'] + '=' + '/home/e.yavarova/alzheimers_research_lala_emiliya/'+ df['subject']
df.head()

,subject,subject_id,to_txt
0,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_007_S_0068_M...,ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correct...,ADNI_007_S_0068_MR_MPR-R__GradWarp__B1_Correct...
1,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_036_S_0945_M...,ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correct...,ADNI_036_S_0945_MR_MPR-R__GradWarp__B1_Correct...
2,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_126_S_0865_M...,ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correct...,ADNI_126_S_0865_MR_MPR-R__GradWarp__B1_Correct...
3,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_002_S_0685_M...,ADNI_002_S_0685_MR_MPR-R__GradWarp__B1_Correct...,ADNI_002_S_0685_MR_MPR-R__GradWarp__B1_Correct...
4,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_016_S_1121_M...,ADNI_016_S_1121_MR_MPR-R__GradWarp__B1_Correct...,ADNI_016_S_1121_MR_MPR-R__GradWarp__B1_Correct...

In [15]:
df.to_csv("subjects_with_paths.csv", index=False, header=False)

In [19]:
df['to_txt'].to_csv("subjects.txt", index=False, header=False)

In [16]:
df[df['subject_id'].str.contains("067_S_1253")]

,subject,subject_id,to_txt
686,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_067_S_1253_M...,ADNI_067_S_1253_MR_MPR-R__GradWarp__B1_Correct...,ADNI_067_S_1253_MR_MPR-R__GradWarp__B1_Correct...
749,MRIs_IMAGES_FILTERED_NOMASKS/ADNI_067_S_1253_M...,ADNI_067_S_1253_MR_MPR-R__GradWarp__B1_Correct...,ADNI_067_S_1253_MR_MPR-R__GradWarp__B1_Correct...

In [ ]:
./brun_fastsurfer.sh \
    --subject_list /home/e.yavarova/alzheimers_research_lala_emiliya/subjects.txt \
    --sd /home/e.yavarova/alzheimers_research_lala_emiliya/FASTSURFER_MASKS \
    --parallel 2 \
    --threads 4 \
    --seg_only \
    --device cuda \
    --statusfile /home/e.yavarova/alzheimers_research_lala_emiliya/FASTSURFER_MASKS/status_fastsurf.txt

SyntaxError: invalid syntax (3797189637.py, line 1)

In [ ]:
import torch
torch.cuda.is_available()   # should return True
torch.cuda.device_count()   # should return 1 or more

2

In [1]:
import pandas as pd

log = pd.read_csv("FASTSURFER_MASKS/status_fastsurf.txt", sep=": ", header=None)
log.columns = ["subject_id", "status"]
log['status'].value_counts()

/tmp/ipykernel_3096639/878567312.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  log = pd.read_csv("FASTSURFER_MASKS/status_fastsurf.txt", sep=": ", header=None)

status
Finished --seg_only successfully      749
Failed --seg_only with exit code 1      7
Name: count, dtype: int64

In [3]:
log[log['status'] != 'Finished --seg_only successfully']

       subject_id                              status
91     057_S_1379  Failed --seg_only with exit code 1
272    033_S_0516  Failed --seg_only with exit code 1
285    094_S_1417  Failed --seg_only with exit code 1
485  023_S_0625_3  Failed --seg_only with exit code 1
528  023_S_0604_2  Failed --seg_only with exit code 1
566  023_S_0604_3  Failed --seg_only with exit code 1
658  128_S_0135_2  Failed --seg_only with exit code 1